In [2]:
import pandas as pd
df = pd.read_csv("All_data.csv")
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df

,hackathon_name,project_name,project_link,is_winner,inspiration,what_it_does,how_we_built_it,challenges,accomplishments,what_we_learned,tech_stack,external_links,github_links,github_summary,what_is_next
0,Cal Hacks 10.0,Audiogroph,https://devpost.com/software/audiogroph,False,With covid ending and people finding new music...,"The project shows events, creators and any NFT...",We used react to build it in vscode and collab...,We had to learn react and navigate through git...,We have successfully built the frontend of the...,Start planning earlier and commit to branches ...,We need a backend to our project.,"css3, html5, javascript, react",['https://github.com/RyanGertz/CalHacksproject'],['https://github.com/RyanGertz/CalHacksproject'],NaN
1,Cal Hacks 10.0,Let It Out,https://devpost.com/software/let-it-out-b2xp8u,False,Understanding and expressing emotions can be a...,The user is first prompted to record a vocal b...,Let It Out is a full stack web app. The front ...,The main challenges we ran into came in our fi...,NaN,We learned how to integrate modern technologie...,NaN,"chakra, flask, hume, mongodb, node.js, openai,...","['https://github.com/apolyeti/calhacks10.0,', ...",['https://github.com/apolyeti/calhacks10.0'],NaN
2,Cal Hacks 10.0,Mood Theremin,https://devpost.com/software/mood-theremin,False,"The theremin, an electronic musical instrument...",Mood Theremin translates your facial expressio...,Our project integrates facial expression analy...,NaN,NaN,NaN,NaN,"css, flask, html, hume, javascript, json, pyth...",['https://github.com/Sepulchre49/CalHacks23'],['https://github.com/Sepulchre49/CalHacks23'],NaN
3,Cal Hacks 10.0,Bay Area Safer Housing (B.A.S.H.),https://devpost.com/software/bay-area-safer-ho...,False,The inspiration initially stems from one membe...,B.A.S.H. searches for affordable housing optio...,Our website's foundation was built on next.js ...,Our difficulties lay in our inexperience with ...,"Conceptually, we believe that our project is m...",We've learned most importantly how to better a...,We are serious in our project and are intent o...,"catalog.data.gov, data.sfgov.org, google-maps,...","['https://github.com/matthewaol/b.a.s.h.,']",['https://github.com/matthewaol/b.a.s.h.'],NaN
4,Cal Hacks 10.0,PawPals,https://devpost.com/software/pawpals-bd8njs,False,"As college students, we both agreed that fun t...","Based on a list of criteria, we prompt OpenAI'...","On the front-end, we utilized Figma to develop...",Some challenges we ran into were the lack of e...,"As a team of two, we were very proud of our fi...",We learned the value of coming up with a plan ...,We hope to deploy the site on Vercel and devel...,"fastapi, figma, openai, python, react.js, sqlite",['https://github.com/Yatsz/PawPals'],['https://github.com/Yatsz/PawPals'],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6912,HackRice 14 2024,Degree Map AI,https://devpost.com/software/degree-planner-ai,False,As current undergraduate students trying to na...,Degree Map AI includes a React front-end and a...,"We first started by working on the scraper, fr...",One challenge we faced was figuring out the be...,We're proud to have successfully connected the...,"We learned to set up OpenAI's ChatGPT, scrape ...","c++, javascript, openai, pyflask, python, react",['https://github.com/april2546/HackRice2024'],['https://github.com/april2546/HackRice2024'],The HackRice2024-DegreeMapAI project is an inn...,"Given the limited amount of time, we were only..."
6913,HackRice 14 2024,Money Mania,https://devpost.com/software/money-mania,False,Our inspiration for this project was this book...,This game teaches people about personal financ...,We built this in Python using PyGame. We split...,None of us have ever participated in a hackath...,We are proud of the fact we have a finished pr...,We learned that creating a layout in PyGame is...,"pygame, python",['https://github.com/ashwinrao1/Hackathon24'],['https://github.com/ashwinrao1/Hackathon24'],"The Hackathon24 project is a ""Personal Finance...",Money Mania will have expansions in the invest...
6914,HackRice 14 2024,AudioAnalyze,https://devpost.com/software/audioanalyze-muw9zk,False,The inspiration behind this project came from ...,NaN,NaN,NaN,NaN,NaN,"ai, generative, lambda-(for-serverless-process...",['https://github.com/Ayush374/Ai_Audio_Analysis'],['https://github.com/Ayush374/Ai_Audio_Analysis'],"The GitHub repository ""Ai_Audio_Analysis"" is d...",NaN
6915,HackRice 14 2024,RestoreIO,https://devpost.com/software/tbd-ir3qd5,False,RestoreIO was created in response to the deman...,NaN,NaN,NaN,NaN,NaN,"ai, computer, computervision, love, mediapipe,...",['https://github.com/OfficialCodeVoyage/HackRi...,['https://github.com/OfficialCodeVoyage/HackRi...,"The GitHub repository ""HackRice14_RecoveryIO,""...",NaN
6916,HackRice 14 2024,MedSure,https://devpost.com/software/tbd-72iomb,False,"As young college students, we are often poorly...",Our key features: 1) Simplify the insurance hu...,Since we wanted to implement a machine learnin...,NaN,NaN,NaN,"mapbox, python, typescript, vite",['https://github.com/leon934/hackrice2425'],['https://github.com/leon934/hackrice2425'],"The `hackrice2425` project, titled ""Insurance ...",NaN

In [4]:
# Only these text columns should be merged
text_cols = [
    'inspiration', 
    'what_it_does', 
    'how_we_built_it', 
    'challenges', 
    'accomplishments', 
    'what_we_learned',
    'what_is_next',
    'tech_stack'
]

# Combine selected columns into one text column
df['all_text'] = df[text_cols].astype(str).apply(lambda x: ' '.join(x), axis=1)

# Clean up text (remove 'nan', brackets, double spaces)
df['all_text'] = (
    df['all_text']
    .str.replace(r"\bnan\b", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)
df = df[['is_winner', 'github_summary', 'all_text']]
df

,is_winner,github_summary,all_text
0,False,['https://github.com/RyanGertz/CalHacksproject'],With covid ending and people finding new music...
1,False,['https://github.com/apolyeti/calhacks10.0'],Understanding and expressing emotions can be a...
2,False,['https://github.com/Sepulchre49/CalHacks23'],"The theremin, an electronic musical instrument..."
3,False,['https://github.com/matthewaol/b.a.s.h.'],The inspiration initially stems from one membe...
4,False,['https://github.com/Yatsz/PawPals'],"As college students, we both agreed that fun t..."
...,...,...,...
6912,False,The HackRice2024-DegreeMapAI project is an inn...,As current undergraduate students trying to na...
6913,False,"The Hackathon24 project is a ""Personal Finance...",Our inspiration for this project was this book...
6914,False,"The GitHub repository ""Ai_Audio_Analysis"" is d...",The inspiration behind this project came from ...
6915,False,"The GitHub repository ""HackRice14_RecoveryIO,""...",RestoreIO was created in response to the deman...
6916,False,"The `hackrice2425` project, titled ""Insurance ...","As young college students, we are often poorly..."